apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: longhorn-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://longhorn.github.io/longhorn
    targetRevision: "1.6.2" # Use the specific chart version you want
    helm:
      valueFiles:
      - ../values/longhorn-values.yaml
    chart: longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true